[project]
name = "rosout-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.1.0",
    "mcp[cli]>=1.12.4",
    "pyyaml>=6.0.2",
]
